#!/bin/bash

# ==============================
# Configurable Variables
# ==============================

# Percentage of total host memory to allocate (e.g., 75 for 75%)
MEMORY_USAGE_PERCENTAGE=75

# Resource ratio for the containers (can be decimal numbers)
RATIO_DB=3.0
RATIO_MANGOS=1.0
RATIO_REALMD=1.0

# CPU share multipliers to ensure higher priority over default containers
# Set the base CPU shares (default is 1024)
BASE_CPU_SHARES=1024

# Multiplier to adjust CPU shares above the default (e.g., 1.5 for 150%)
CPU_SHARE_MULTIPLIER_MANGOS=1.5
CPU_SHARE_MULTIPLIER_REALMD=1.5
CPU_SHARE_MULTIPLIER_DB=4.5  # To maintain the ratio

# ==============================
# Script Logic (No Need to Modify Below)
# ==============================

# 1. Get total system memory in bytes
total_mem_kb=$(grep MemTotal /proc/meminfo | awk '{print $2}')
total_mem_bytes=$(($total_mem_kb * 1024))

# 2. Calculate specified percentage of total memory
mem_limit=$(awk "BEGIN {printf \"%.0f\", $total_mem_bytes * $MEMORY_USAGE_PERCENTAGE / 100}")

# 3. Total ratio parts
total_parts=$(awk "BEGIN {print $RATIO_DB + $RATIO_MANGOS + $RATIO_REALMD}")

# 4. Calculate memory limits for each container based on the ratio
mem_db=$(awk "BEGIN {printf \"%.0f\", $mem_limit * $RATIO_DB / $total_parts}")
mem_mangos=$(awk "BEGIN {printf \"%.0f\", $mem_limit * $RATIO_MANGOS / $total_parts}")
mem_realmd=$(awk "BEGIN {printf \"%.0f\", $mem_limit * $RATIO_REALMD / $total_parts}")

# 5. Convert memory limits to bytes with 'b' suffix
mem_db_limit="${mem_db}b"
mem_mangos_limit="${mem_mangos}b"
mem_realmd_limit="${mem_realmd}b"

# 6. Calculate CPU shares for each container
cpu_shares_db=$(awk "BEGIN {printf \"%.0f\", $BASE_CPU_SHARES * $CPU_SHARE_MULTIPLIER_DB}")
cpu_shares_mangos=$(awk "BEGIN {printf \"%.0f\", $BASE_CPU_SHARES * $CPU_SHARE_MULTIPLIER_MANGOS}")
cpu_shares_realmd=$(awk "BEGIN {printf \"%.0f\", $BASE_CPU_SHARES * $CPU_SHARE_MULTIPLIER_REALMD}")

# 7. Write variables to the .env file
cat > .env <<EOL
# Resource limits generated by set_resource_limits.sh

# Memory Limits
MEM_LIMIT_DB=${mem_db_limit}
MEM_LIMIT_MANGOS=${mem_mangos_limit}
MEM_LIMIT_REALMD=${mem_realmd_limit}

# CPU Shares
CPU_SHARES_DB=${cpu_shares_db}
CPU_SHARES_MANGOS=${cpu_shares_mangos}
CPU_SHARES_REALMD=${cpu_shares_realmd}
EOL

echo "Resource limits have been set in the .env file:"
cat .env
